livereload: true

baseurl: /
permalink: /blog/:title

exclude: ['build', 'README.md', 'nginx.conf', 'Gemfile', 'Gemfile.lock', 'node_modules']
include: ['_redirects']

markdown: kramdown
highlighter: rouge
